### ISSUE TITLE
Support of HTTP/2

### ISSUE THREAD

**Issue by zxcso** [Eugeny/ajenti-v#188]
Nginx has started the process to support http/2. And now they have release the first patch for nginx to support http/2, but ajenti-v don't support http/2, can it support http/2?

**Comment by Xefir** [comment]
Maybe it's a little bit to soon.

All current distributions will not apply this patch before a while, maybe waiting for a global release could be a better idea.

If you really want this feature, your could modify the ajenti nginx_templates.py to fit your needs.

**Comment by kraftbj** [comment]
the nginx development line in Ubuntu (really, `mainline`) has 1.9.6, which supports http2.

I'm not familiar with Python, but could we condintionally check for which version of nginx is present on the system and apply spdy or http2 accordingly?

**Comment by danutzzzz** [comment]
In my case (nginx 1.9.7), using SPDY results in a warning and it seems that it has been replaced already with http2. Having an option in Ajenti-V for HTTP2 would be a nice option. 

(Already changed it myself in nginx.py on my install.)

**Comment by ragnarkarlsson** [comment]
danutzzzz what change did you make to nginx.py out of curiosity? I presume it was in the region of lines 118 to 121?

**Comment by danutzzzz** [comment]
on my server, in /var/lib/ajenti/plugins/vh-nginx/nginx.py I replaced SPDY on line 120 with HTTP2: 
 ' http2' if x.spdy else '',
Of course, this is a temporary solution and it does not replace the text "SPDY" in the admin, it just does the job by replacing in the config files.

**Comment by Xefir** [comment]
It's not outdated, since the http2 isn't in the stable branch of nginx development.

Yes it's on mainline branch, but it's the current stable dev version, not the very stable witch will be ready to package on regular serious distribs like debian or ubuntu LTS

I made a compromise to make everyone happy. My latest PR will add the checkbox and keep the spdy one too. You have the choice, check the one you want :)
