### ISSUE TITLE
Why Courier?

### ISSUE THREAD

**Issue by bbbenji** [Eugeny/ajenti-v#196]
What where the deciding factors in going with Courier for IMAP in Ajenti? I am looking to to migrate emails from our old server which uses Dovecot to our new one with Ajenti and finding it hard to find any documentation on the process. Upon reading more into Courier and Dovecot, it seems like it is a consensus that Dovecot is superior.

Also if anyone has any info on migrating from Dovecot to Courier please let me know.

**Comment by DDevine** [comment]
To migrate between two MDAs you can always use a script to download all mail and then re-inject it back into the new server. I used imapsync (https://github.com/imapsync/imapsync) a few years ago when I first moved to self-hosting mail. 

However, Dovecot also has a Courier Maildir migration script which can be used if you used Maildir format under Courier. Despite Maildir being a documented standard is always implemented differently. The script is in the Dovecot 1.x docs (http://wiki.dovecot.org/Migration/Courier) but the Dovecot 1.x and 2.x Maildirs are compatible (IIRC) so it should work I think. Keep a backup of Courier's Maildir and give it a shot I guess - if it doesn't work then imapsync certainly will.

I currently use Dovecot (not in Ajenti) and it's great however I am seriously looking at moving towards Cyrus IMAP. The reason is that the new version of Cyrus will have 3 killer features: CalDAV, CardDAV and JMAP. It's a pretty cool server and is in heavy use at Fastmail however I wish documentation was a bit more comprehensive.

I looked into the Ajenti code and it looks like the mail stuff was written with extension in mind so that's a relief. Theoretically you can inherit MailBackend in vh-mail/api.py and implement a Dovecot - or in my case Cyrus - mail backend.

Courier was definitely relatively simple to integrate into Ajenti - so maybe that's why Courier in the first place besides the author's personal choice (hey it works!).

This is an itch I'm interested in scratching, but no promises unfortunately.

**Comment by bbbenji** [comment]
Just did some reading on Cyrus. Sounds very exciting. I would love to see it implemented into Ajenti.
